apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
      - name: flask-calculator
        image: flask-calculator:latest
        ports:
        - containerPort: 5000
