apiVersion: v1
kind: Service
metadata:
  name: flask-calculator-service
spec:
  type: NodePort
  selector:
    app: flask-calculator
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
